version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: zoti-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zoti360
      POSTGRES_DB: zoti_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: zoti-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: zoti_db
      DB_USER: admin
      DB_PASSWORD: zoti360
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: